{{- if .Values.config.elasticsearch.internal }}
apiVersion: kubedb.com/v1alpha1
kind: Elasticsearch
metadata:
  name: {{ template "<%- _.kebabCase(name) %>.fullname" . }}-elasticsearch
  labels:
    app: {{ template "<%- _.kebabCase(name) %>.name" . }}-elasticsearch
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  {{- if .Values.persistence.backup.enabled }}
  annotations:
    stash.appscode.com/backup-blueprint: {{ template "<%- _.kebabCase(name) %>.fullname" . }}-kubedb
  {{- end }}
spec:
  version: {{ .Values.config.elasticsearch.version | quote }}
  configSource:
    configMap:
      name: {{ template "<%- _.kebabCase(name) %>.fullname" . }}-elasticsearch
  {{- if .Values.config.elasticsearch.prometheus }}
  monitor:
    agent: prometheus.io/builtin
  {{- end }}
  {{- if (gt (.Values.config.elasticsearch.replicas | int64) 1) }}
  replicas: {{ .Values.config.elasticsearch.replicas }}
  {{- end }}
  {{- if .Values.persistence.enabled }}
  storageType: Durable
  storage:
    {{- if .Values.persistence.storageClass }}
    {{- if (eq "-" .Values.persistence.storageClass) }}
    storageClassName: ''
    {{- else }}
    storageClassName: {{ .Values.persistence.storageClass }}
    {{- end }}
    {{- end }}
    accessModes:
      - {{ .Values.persistence.accessMode }}
    resources:
      requests:
        storage: {{ .Values.persistence.size }}
  {{- else }}
  storageType: Ephemeral
  {{- end }}
  serviceTemplate:
    metadata:
      annotations:
        passMe: ToService
    spec:
      type: {{ .Values.service.elasticsearch.type }}
      {{- if (or (eq .Values.service.elasticsearch.type "LoadBalancer") (eq .Values.service.elasticsearch.type "NodePort")) }}
      externalTrafficPolicy: {{ .Values.service.elasticsearch.externalTrafficPolicy }}
      {{- end }}
      ports:
        - name: elasticsearch
          port: 9200
          targetPort: elasticsearch
          {{- if (and (eq .Values.service.elasticsearch.type "NodePort") (not (empty .Values.service.elasticsearch.nodePorts.elasticsearch))) }}
          nodePort: {{ .Values.service.elasticsearch.nodePorts.elasticsearch }}
          {{- end }}
  replicaServiceTemplate:
    annotations:
      passMe: ToReplicaService
    spec:
      type: {{ .Values.service.elasticsearch.type }}
      {{- if (or (eq .Values.service.elasticsearch.type "LoadBalancer") (eq .Values.service.elasticsearch.type "NodePort")) }}
      externalTrafficPolicy: {{ .Values.service.elasticsearch.externalTrafficPolicy }}
      {{- end }}
      ports:
        - name: elasticsearch
          port: 9200
          targetPort: elasticsearch
          {{- if (and (eq .Values.service.elasticsearch.type "NodePort") (not (empty .Values.service.elasticsearch.nodePorts.elasticsearch))) }}
          nodePort: {{ .Values.service.elasticsearch.nodePorts.elasticsearch }}
          {{- end }}
  updateStrategy:
    type: RollingUpdate
  {{- if .Values.persistence.enabled }}
  terminationPolicy: Pause
  {{- else }}
  terminationPolicy: Delete
  {{- end }}
{{- end }}
{{- if .Values.persistence.backup.enabled }}
---
apiVersion: appcatalog.appscode.com/v1alpha1
kind: AppBinding
metadata:
  name: {{ template "<%- _.kebabCase(name) %>.fullname" . }}-elasticsearch
  labels:
    app: {{ template "<%- _.kebabCase(name) %>.name" . }}-elasticsearch
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    stash.appscode.com/backup-blueprint: {{ template "<%- _.kebabCase(name) %>.fullname" . }}-kubedb
spec:
  clientConfig:
    service:
      name: {{ template "<%- _.kebabCase(name) %>.fullname" . }}-elasticsearch
      path: /
      port: 5432
      query: sslmode=disable
      scheme: elasticsearchql
  secret:
    name: {{ template "<%- _.kebabCase(name) %>.sharedname" . }}-elasticsearch-auth
  secretTransforms:
    - renameKey:
        from: ELASTICSEARCH_USER
        to: username
    - renameKey:
        from: ELASTICSEARCH_PASSWORD
        to: password
  type: kubedb.com/elasticsearch
  version: {{ .Values.config.elasticsearch.version | quote }}
{{- if (not (empty .Values.persistence.backup.restore.elasticsearchSnapshot)) }}
{{- $restore := .Values.persistence.backup.restore }}
---
apiVersion: stash.appscode.com/v1alpha1
kind: Repository
metadata:
  name: {{ template "<%- _.kebabCase(name) %>.fullname" . }}-restore-elasticsearch
  labels:
    app: {{ template "<%- _.kebabCase(name) %>.name" . }}-restore-elasticsearch
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  backend:
    {{ .Values.persistence.backup.type }}:
      {{- if (or (eq "gcs" .Values.persistence.backup.type) (eq "s3" .Values.persistence.backup.type)) }}
      bucket: {{ .Values.persistence.backup.bucket | quote }}
      {{- end }}
      {{- if (eq "s3" .Values.persistence.backup.type) }}
      endpoint: {{ .Values.persistence.backup.endpoint | quote }}
      {{- end }}
      {{- if (eq "azure" .Values.persistence.backup.type) }}
      container: {{ .Values.persistence.backup.container | quote }}
      {{- end }}
      {{- $fullname := (empty $restore.fullname | ternary (include "<%- _.kebabCase(name) %>.fullname" .) $restore.fullname) }}
      prefix: '{{ .Values.persistence.backup.prefix }}/${TARGET_NAMESPACE}/elasticsearch/{{ $fullname }}-elasticsearch'
    storageSecretName: {{ template "<%- _.kebabCase(name) %>.fullname" . }}-backup
---
apiVersion: stash.appscode.com/v1beta1
kind: RestoreSession
metadata:
  name: {{ template "<%- _.kebabCase(name) %>.fullname" . }}-elasticsearch
  labels:
    app: {{ template "<%- _.kebabCase(name) %>.name" . }}-elasticsearch
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    kubedb.com/kind: Elasticsearch
spec:
  driver: Restic
  task:
    name: elasticsearch-restore-${TARGET_APP_VERSION}
  repository:
    name: {{ template "<%- _.kebabCase(name) %>.fullname" . }}-restore-elasticsearch
  target:
    ref:
      apiVersion: appcatalog.appscode.com/v1alpha1
      kind: AppBinding
      name: {{ template "<%- _.kebabCase(name) %>.fullname" . }}-elasticsearch
  rules:
    - snapshots:
      - {{ $restore.elasticsearchSnapshot }}
{{- end }}
{{- end }}
