{{- if .Values.config.elasticsearch.internal }}
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "<%- name %>.fullname" . }}-elasticsearch
  labels:
    app: {{ template "<%- name %>.name" . }}-elasticsearch
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  strategy:
    type: {{ .Values.config.updateStrategy }}
  template:
    metadata:
      labels:
        app: {{ template "<%- name %>.name" . }}-elasticsearch
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ template "<%- name %>.fullname" . }}-elasticsearch
          image: {{ .Values.images.elasticsearch.repository }}:{{ .Values.images.elasticsearch.tag }}
          imagePullPolicy: {{ .Values.config.imagePullPolicy }}
          ports:
            - name: container
              containerPort: 9200
          volumeMounts:
            - name: data
              mountPath: /usr/share/elasticsearch/data
              subPath: elasticsearch
          env:
            - name: discovery.type
              value: single-node
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "<%- name %>.fullname" . }}
                  key: elasticsearch_password
          livenessProbe:
            tcpSocket:
              port: container
{{ toYaml .Values.probes.liveness | indent 12 }}
          readinessProbe:
            tcpSocket:
              port: container
{{ toYaml .Values.probes.readiness | indent 12 }}<%- include('../volumes'); %>
{{- end }}
