{{- if .Values.config.mysql.internal }}
apiVersion: kubedb.com/v1alpha1
kind: MySQL
metadata:
  name: {{ template "<%- _.kebabCase(name) %>.fullname" . }}-mysql
  labels:
    app: {{ template "<%- _.kebabCase(name) %>.name" . }}-mysql
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  {{- if .Values.persistence.backup.enabled }}
  annotations:
    stash.appscode.com/backup-blueprint: {{ template "<%- _.kebabCase(name) %>.fullname" . }}-kubedb
  {{- end }}
spec:
  version: {{ .Values.config.mysql.version | quote }}
  configSource:
    configMap:
      name: {{ template "<%- _.kebabCase(name) %>.fullname" . }}-mysql
  {{- if (not (empty .Values.persistence.backup.restore.mysqlSnapshot)) }}
  databaseSecret:
    secretName: {{ template "<%- _.kebabCase(name) %>.sharedname" . }}-mysql-auth
  {{- end }}
  {{- if .Values.config.mysql.prometheus }}
  monitor:
    agent: prometheus.io/builtin
  {{- end }}
  {{- if (gt (.Values.config.mysql.replicas | int64) 1) }}
  replicas: {{ .Values.config.mysql.replicas }}
  {{- end }}
  {{- if .Values.persistence.enabled }}
  storageType: Durable
  storage:
    {{- if .Values.persistence.storageClass }}
    {{- if (eq "-" .Values.persistence.storageClass) }}
    storageClassName: ''
    {{- else }}
    storageClassName: {{ .Values.persistence.storageClass }}
    {{- end }}
    {{- end }}
    accessModes:
      - {{ .Values.persistence.accessMode }}
    resources:
      requests:
        storage: {{ .Values.persistence.size }}
  {{- else }}
  storageType: Ephemeral
  {{- end }}
  {{- if (empty .Values.persistence.backup.restore.mysqlSnapshot) }}
  init:
    scriptSource:
      configMap:
        name: {{ template "<%- _.kebabCase(name) %>.fullname" . }}-mysql-init
  {{- end }}
  serviceTemplate:
    metadata:
      annotations:
        passMe: ToService
    spec:
      type: {{ .Values.service.mysql.type }}
      {{- if (or (eq .Values.service.mysql.type "LoadBalancer") (eq .Values.service.mysql.type "NodePort")) }}
      externalTrafficPolicy: {{ .Values.service.mysql.externalTrafficPolicy }}
      {{- end }}
      ports:
        - name: mysql
          port: 3306
          targetPort: mysql
          {{- if (and (eq .Values.service.mysql.type "NodePort") (not (empty .Values.service.mysql.nodePorts.mysql))) }}
          nodePort: {{ .Values.service.mysql.nodePorts.mysql }}
          {{- end }}
  replicaServiceTemplate:
    annotations:
      passMe: ToReplicaService
    spec:
      type: {{ .Values.service.mysql.type }}
      {{- if (or (eq .Values.service.mysql.type "LoadBalancer") (eq .Values.service.mysql.type "NodePort")) }}
      externalTrafficPolicy: {{ .Values.service.mysql.externalTrafficPolicy }}
      {{- end }}
      ports:
        - name: mysql
          port: 3306
          targetPort: mysql
          {{- if (and (eq .Values.service.mysql.type "NodePort") (not (empty .Values.service.mysql.nodePorts.mysql))) }}
          nodePort: {{ .Values.service.mysql.nodePorts.mysql }}
          {{- end }}
  updateStrategy:
    type: RollingUpdate
  {{- if .Values.persistence.enabled }}
  terminationPolicy: Pause
  {{- else }}
  terminationPolicy: Delete
  {{- end }}
{{- end }}
{{- if .Values.persistence.backup.enabled }}
---
apiVersion: appcatalog.appscode.com/v1alpha1
kind: AppBinding
metadata:
  name: {{ template "<%- _.kebabCase(name) %>.fullname" . }}-mysql
  labels:
    app: {{ template "<%- _.kebabCase(name) %>.name" . }}-mysql
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    stash.appscode.com/backup-blueprint: {{ template "<%- _.kebabCase(name) %>.fullname" . }}-kubedb
spec:
  clientConfig:
    service:
      name: {{ template "<%- _.kebabCase(name) %>.fullname" . }}-mysql
      path: /
      port: 3306
      query: sslmode=disable
      scheme: mysql
  type: kubedb.com/mysql
{{- if (not (empty .Values.persistence.backup.restore.mysqlSnapshot)) }}
{{- $restore := .Values.persistence.backup.restore }}
---
apiVersion: stash.appscode.com/v1alpha1
kind: Repository
metadata:
  name: {{ template "<%- _.kebabCase(name) %>.fullname" . }}-restore-mysql
  labels:
    app: {{ template "<%- _.kebabCase(name) %>.name" . }}-restore-mysql
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  backend:
    {{ .Values.persistence.backup.type }}:
      {{- if (or (eq "gcs" .Values.persistence.backup.type) (eq "s3" .Values.persistence.backup.type)) }}
      bucket: {{ .Values.persistence.backup.bucket | quote }}
      {{- end }}
      {{- if (eq "s3" .Values.persistence.backup.type) }}
      endpoint: {{ .Values.persistence.backup.endpoint | quote }}
      {{- end }}
      {{- if (eq "azure" .Values.persistence.backup.type) }}
      container: {{ .Values.persistence.backup.container | quote }}
      {{- end }}
      prefix: '{{ .Values.persistence.backup.prefix }}/${TARGET_NAMESPACE}/mysql'
    storageSecretName: {{ template "<%- _.kebabCase(name) %>.fullname" . }}-backup
---
apiVersion: stash.appscode.com/v1beta1
kind: RestoreSession
metadata:
  name: {{ template "<%- _.kebabCase(name) %>.fullname" . }}-mysql
  labels:
    app: {{ template "<%- _.kebabCase(name) %>.name" . }}-mysql
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    kubedb.com/kind: Mysql
spec:
  driver: Restic
  task:
    name: mysql-restore-{{ .Values.config.mysql.version }}
  repository:
    name: {{ template "<%- _.kebabCase(name) %>.fullname" . }}-restore-mysql
  target:
    ref:
      apiVersion: appcatalog.appscode.com/v1alpha1
      kind: AppBinding
      name: {{ template "<%- _.kebabCase(name) %>.fullname" . }}-mysql
  rules:
    - snapshots:
      - {{ $restore.mysqlSnapshot }}
{{- end }}
{{- end }}
