{{- if (not (or .Values.config.postgres.url .Values.config.postgres.host)) }}
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "<%- name %>.fullname" . }}-postgres
  labels:
    app: {{ template "<%- name %>.name" . }}-postgres
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  template:
    metadata:
      labels:
        app: {{ template "<%- name %>.name" . }}-postgres
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ template "<%- name %>.fullname" . }}-postgres
          image: {{ .Values.images.postgres.repository }}:{{ .Values.images.postgres.tag }}
          imagePullPolicy: {{ .Values.images.postgres.pullPolicy }}
          ports:
            - name: container
              containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
              subPath: postgres
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: {{ template "<%- name %>.fullname" . }}
                  key: postgres_database
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ template "<%- name %>.fullname" . }}
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "<%- name %>.fullname" . }}
                  key: postgres_password
          livenessProbe:
            tcpSocket:
              port: container
{{ toYaml .Values.probes.liveness | indent 12 }}
          readinessProbe:
            tcpSocket:
              port: container
{{ toYaml .Values.probes.readiness | indent 12 }}<%- include('../volumes'); %>
{{- end }}
