{{- if .Values.config.postgres.internal }}
apiVersion: kubedb.com/v1alpha1
kind: Postgres
metadata:
  name: {{ template "<%- _.kebabCase(name) %>.fullname" . }}-postgres
  labels:
    app: {{ template "<%- _.kebabCase(name) %>.name" . }}-postgres
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  {{- if .Values.persistence.backup.enabled }}
  annotations:
    stash.appscode.com/backup-blueprint: {{ template "<%- _.kebabCase(name) %>.fullname" . }}-kubedb
  {{- end }}
spec:
  version: {{ .Values.config.postgres.version | quote }}
  configSource:
    configMap:
      name: {{ template "<%- _.kebabCase(name) %>.fullname" . }}-postgres
  standbyMode: {{ .Values.config.postgres.standbyMode | quote }}
  {{- if (not (empty .Values.persistence.backup.restore.postgresSnapshot)) }}
  databaseSecret:
    secretName: {{ template "<%- _.kebabCase(name) %>.sharedname" . }}-postgres-auth
  {{- end }}
  {{- if .Values.config.postgres.prometheus }}
  monitor:
    agent: prometheus.io/builtin
  {{- end }}
  {{- if (gt (.Values.config.postgres.replicas | int64) 1) }}
  replicas: {{ .Values.config.postgres.replicas }}
  {{- end }}
  {{- if .Values.persistence.enabled }}
  storageType: Durable
  storage:
    {{- if .Values.persistence.storageClass }}
    {{- if (eq "-" .Values.persistence.storageClass) }}
    storageClassName: ''
    {{- else }}
    storageClassName: {{ .Values.persistence.storageClass }}
    {{- end }}
    {{- end }}
    accessModes:
      - {{ .Values.persistence.accessMode }}
    resources:
      requests:
        storage: {{ .Values.persistence.size }}
  {{- else }}
  storageType: Ephemeral
  {{- end }}
  {{- if (empty .Values.persistence.backup.restore.postgresSnapshot) }}
  init:
    scriptSource:
      configMap:
        name: {{ template "<%- _.kebabCase(name) %>.fullname" . }}-postgres-init
  {{- end }}
  serviceTemplate:
    metadata:
      annotations:
        passMe: ToService
    spec:
      type: {{ .Values.service.postgres.type }}
      {{- if (or (eq .Values.service.postgres.type "LoadBalancer") (eq .Values.service.postgres.type "NodePort")) }}
      externalTrafficPolicy: {{ .Values.service.postgres.externalTrafficPolicy }}
      {{- end }}
      ports:
        - name: postgres
          port: 5432
          targetPort: postgres
          {{- if (and (eq .Values.service.postgres.type "NodePort") (not (empty .Values.service.postgres.nodePorts.postgres))) }}
          nodePort: {{ .Values.service.postgres.nodePorts.postgres }}
          {{- end }}
  replicaServiceTemplate:
    annotations:
      passMe: ToReplicaService
    spec:
      type: {{ .Values.service.postgres.type }}
      {{- if (or (eq .Values.service.postgres.type "LoadBalancer") (eq .Values.service.postgres.type "NodePort")) }}
      externalTrafficPolicy: {{ .Values.service.postgres.externalTrafficPolicy }}
      {{- end }}
      ports:
        - name: postgres
          port: 5432
          targetPort: postgres
          {{- if (and (eq .Values.service.postgres.type "NodePort") (not (empty .Values.service.postgres.nodePorts.postgres))) }}
          nodePort: {{ .Values.service.postgres.nodePorts.postgres }}
          {{- end }}
  updateStrategy:
    type: RollingUpdate
  {{- if .Values.persistence.enabled }}
  terminationPolicy: Pause
  {{- else }}
  terminationPolicy: Delete
  {{- end }}
{{- end }}
{{- if .Values.persistence.backup.enabled }}
---
apiVersion: appcatalog.appscode.com/v1alpha1
kind: AppBinding
metadata:
  name: {{ template "<%- _.kebabCase(name) %>.fullname" . }}-postgres
  labels:
    app: {{ template "<%- _.kebabCase(name) %>.name" . }}-postgres
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    stash.appscode.com/backup-blueprint: {{ template "<%- _.kebabCase(name) %>.sharedname" . }}-postgres
spec:
  clientConfig:
    service:
      name: {{ template "<%- _.kebabCase(name) %>.fullname" . }}-postgres
      path: /
      port: 5432
      query: sslmode=disable
      scheme: postgresql
  secretTransforms:
    - renameKey:
        from: POSTGRES_USER
        to: username
    - renameKey:
        from: POSTGRES_PASSWORD
        to: password
  type: kubedb.com/postgres
{{- if (not (empty .Values.persistence.backup.restore.postgresSnapshot)) }}
{{- $restore := .Values.persistence.backup.restore }}
---
apiVersion: stash.appscode.com/v1beta1
kind: RestoreSession
metadata:
  name: {{ template "<%- _.kebabCase(name) %>.fullname" . }}-postgres
  labels:
    app: {{ template "<%- _.kebabCase(name) %>.name" . }}-postgres
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    kubedb.com/kind: Postgres
spec:
  driver: Restic
  task:
    name: postgres-restore-{{ .Values.config.postgres.version }}
  repository:
    name: {{ template "<%- _.kebabCase(name) %>.sharedname" . }}-postgres
  target:
    ref:
      apiVersion: appcatalog.appscode.com/v1alpha1
      kind: AppBinding
      name: {{ template "<%- _.kebabCase(name) %>.fullname" . }}-postgres
  rules:
    - snapshots:
      - {{ $restore.postgresSnapshot }}
{{- end }}
{{- end }}
