{{- if .Values.config.elasticsearch.internal }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "<%- name %>.fullname" . }}-elasticsearch
  labels:
    app: {{ template "<%- name %>.name" . }}-elasticsearch
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - name: elasticsearch
      port: 9200
      targetPort: container
  selector:
    app: {{ template "<%- name %>.name" . }}-elasticsearch
    release: {{ .Release.Name }}
{{- end }}
