{{- if .Values.config.mongo.internal }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "<%- name %>.fullname" . }}-mongo
  labels:
    app: {{ template "<%- name %>.name" . }}-mongo
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - name: mongo
      port: 27017
      targetPort: container
  selector:
    app: {{ template "<%- name %>.name" . }}-mongo
    release: {{ .Release.Name }}
{{- end }}
