apiVersion: v1
kind: Service
metadata:
  name: {{ template "<%- name %>.fullname" . }}-<%- _.kebabCase(workload.name) %>
  labels:
    app: {{ template "<%- name %>.name" . }}-<%- _.kebabCase(workload.name) %>
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: container
  selector:
    app: {{ template "<%- name %>.name" . }}-<%- _.kebabCase(workload.name) %>
    release: {{ .Release.Name }}
