apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "<%- name %>.fullname" . }}-redis
  labels:
    app: {{ template "<%- name %>.name" . }}-redis
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  redis.conf: {{ .Values.config.redis.customConfig | quote }}
