{{- if .Values.persistence.backup.enabled }}
apiVersion: stash.appscode.com/v1alpha1
kind: Restic
metadata:
  name: {{ template "<%- name %>.fullname" . }}-<%- workload.name %>
  labels:
    app: {{ template "<%- name %>.name" . }}-<%- workload.name %>
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "<%- name %>.name" . }}-<%- workload.name %>
  fileGroups:<% for (var i = 0; i < workload.volumes.length; i++) { var volume = workload.volumes[i]; %>
    - path: '<%- volume.mountPath %>'
      retentionPolicyName: 'retention-policy'<% } %>
  backend:
    s3:
      endpoint: {{ .Values.persistence.backup.endpoint | quote }}
      bucket: {{ .Values.persistence.backup.bucket | quote }}
      prefix: {{ .Values.persistence.backup.prefix | quote }}
    storageSecretName: {{ template "<%- name %>.fullname" . }}-backup
  schedule: {{ .Values.persistence.backup.schedule | quote }}
  volumeMounts:<% for (var i = 0; i < workload.volumes.length; i++) { var volume = workload.volumes[i]; %>
    - name: <%- volume.name %>
      mountPath: '<%- volume.mountPath %>'<% if (volume.subPath) { %>
      subPath: <%- volume.subPath %><% }} %>
  retentionPolicies:
    - name: 'retention-policy'
      keepLast: {{ .Values.persistence.backup.keepLast }}
      prune: true
{{- end }}
