apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "<%= name %>.fullname" . }}-<%= workload.name %>
  labels:
    app: {{ template "<%= name %>.name" . }}-<%= workload.name %>
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  template:
    metadata:
      labels:
        app: {{ template "<%= name %>.name" . }}-<%= workload.name %>
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ template "<%= name %>.fullname" . }}-<%= workload.name %>
          image: {{ .Values.images.<%= workload.name %>.repository }}:{{ .Values.images.<%= workload.name %>.tag }}
          imagePullPolicy: {{ .Values.images.<%= workload.name %>.pullPolicy }}
          ports:
            - name: container
              containerPort: <%= workload.port %>
          livenessProbe:
            httpGet:
              path: /
              port: container
{{ toYaml .Values.probes.liveness | indent 12 }}
          readinessProbe:
            httpGet:
              path: /
              port: container
{{ toYaml .Values.probes.readiness | indent 12 }}
