{{- if (and .Values.ingress.enabled .Values.ingress.ssl) }}
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ template "rocketchat.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  secretName: letsencrypt-staging
  issuerRef:
    name: {{ .Values.issuer.name }}
    kind: {{ .Values.issuer.kind }}
  commonName: '{{ (index .Values.ingress.hosts.<%= publicDeployments[0].name %> 0).name }}'<% if (publicDeployments.length > 1) { %>
  dnsNames:<% for (var i = 1; i < publicDeployments.length; i++) { deployment = deployments[i]; %>
    - '{{ (index .Values.ingress.hosts.<%= deployment.name %> 0).name }}'<% } %><% } %>
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:<% for (var i = 0; i < publicDeployments.length; i++) { deployment = deployments[i]; %>
        - '{{ (index .Values.ingress.hosts.<%= deployment.name %> 0).name }}'<% } %>
{{- end }}
