apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "<%- _.kebabCase(name) %>.fullname" . }}-<%- _.kebabCase(workload.name) %>
  labels:
    app: {{ template "<%- _.kebabCase(name) %>.name" . }}-<%- _.kebabCase(workload.name) %>
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}<% if (workload.volumes.length) { %>
  {{- if .Values.persistence.backup.enabled }}
  annotations:
    stash.appscode.com/backup-blueprint: {{ template "<%- _.kebabCase(name) %>.fullname" . }}-data
    stash.appscode.com/target-paths: /_data
    stash.appscode.com/volume-mounts: 'data:/_data'
  {{- end }}<% } %>
spec:
  selector:
    matchLabels:
      app: {{ template "<%- _.kebabCase(name) %>.name" . }}-<%- _.kebabCase(workload.name) %>
      release: {{ .Release.Name }}
  strategy:
    type: {{ .Values.config.updateStrategy }}
  template:
    metadata:
      labels:
        app: {{ template "<%- _.kebabCase(name) %>.name" . }}-<%- _.kebabCase(workload.name) %>
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ template "<%- _.kebabCase(name) %>.fullname" . }}-<%- _.kebabCase(workload.name) %>
          image: {{ .Values.images.<%- _.camelCase(workload.name) %>.repository }}:{{ .Values.images.<%- _.camelCase(workload.name) %>.tag }}
          imagePullPolicy: {{ .Values.config.imagePullPolicy }}
          ports:
            - name: container
              containerPort: <%- workload.port %><% if (workload.volumes.length) { %>
          volumeMounts:
            - name: data
              mountPath: /_data<% for (var i = 0; i < workload.volumes.length; i++) { var volume = workload.volumes[i]; %>
            - name: data
              mountPath: '<%- volume.mountPath %>'
              subPath: <%- volume.subPath %><% } if (volume.readOnly) { %>
              readOnly: true<% }} %>
          env: []<% if (workload.healthcheck !== 'none') { %>
          livenessProbe:
            <%- workload.healthcheck %>:<% if (workload.healthcheckPath) { %>
              path: <%- workload.healthcheckPath %><% } %>
              port: container
{{ toYaml .Values.probes.liveness | indent 12 }}
          readinessProbe:
            <%- workload.healthcheck %>:<% if (workload.healthcheckPath) { %>
              path: <%- workload.healthcheckPath %><% } %>
              port: container
{{ toYaml .Values.probes.readiness | indent 12 }}<% } %><%- include('./volumes'); %><% if (workload.volumes.length) { %>
{{- if (and .Values.persistence.backup.enabled (not (empty .Values.persistence.backup.restore.<%- _.camelCase(workload.name) %>Snapshot))) }}
{{- $restore := .Values.persistence.backup.restore }}
---
apiVersion: stash.appscode.com/v1beta1
kind: RestoreSession
metadata:
  name: {{ template "<%- _.kebabCase(name) %>.fullname" . }}-<%- _.kebabCase(workload.name) %>
  labels:
    app: {{ template "<%- _.kebabCase(name) %>.name" . }}-<%- _.kebabCase(workload.name) %>
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  driver: Restic
  repository:
    name: {{ template "<%- _.kebabCase(name) %>.fullname" . }}-<%- _.kebabCase(workload.name) %>
  rules:
    - snapshots:
        - {{ $restore.<%- _.camelCase(workload.name) %>Snapshot }}
  target:
    paths:
      /_data
    ref:
      apiVersion: apps/v1
      kind: Deployment
      name: {{ template "<%- _.kebabCase(name) %>.fullname" . }}-<%- _.kebabCase(workload.name) %>
    volumeMounts:
      - name: data
        mountPath: /_data
{{- end }}<% } %>
