apiVersion: v1
kind: Secret
metadata:
  name: {{ template "rocketchat.fullname" . }}
  labels:
    app: {{ template "rocketchat.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{- $mongo := .Values.config.mongo }}
  {{- if (or $mongo.url $mongo.username $mongo.password) }}
  {{- if $mongo.url }}
  mongo_url: {{ $mongo.url | b64enc }}
  {{- else }}
  {{- $mongo_url := (printf "%s%s%s%s%s%s%s%s%s%s" "mongodb://" $mongo.username ":" $mongo.password "@" $mongo.host ":" $mongo.port "/" $mongo.database) }}
  mongo_url: {{ $mongo_url | b64enc }}
  {{- end }}
  {{- end }}
  email_smtp_password: {{ .Values.config.email.smtp.password | b64enc }}
