apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "<%= name %>.fullname" . }}-<%= workload.name %>
  labels:
    app: {{ template "<%= name %>.name" . }}-<%= workload.name %>
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  template:
    metadata:
      labels:
        app: {{ template "<%= name %>.name" . }}-<%= workload.name %>
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ template "<%= name %>.fullname" . }}-<%= workload.name %>
          image: {{ .Values.images.<%= workload.name %>.repository }}:{{ .Values.images.<%= workload.name %>.tag }}
          imagePullPolicy: {{ .Values.images.<%= workload.name %>.pullPolicy }}
          ports:
            - name: container
              containerPort: <%= deployment.port %><% if (deployment.persistence) { %>

          volumeMounts:
            - name: data
              mountPath: /data/db
              subPath: mongo<% } %>
          env: []<% if (deployment.persistence) { %>
      volumes:
        - name: data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "rocketchat.fullname" . ) }}
          {{- else }}
          emptyDir: {}
          {{- end }}<% } %>
